config/routes.rb
Zsdou::Application.routes.draw do 
  

  resources :listing_cards

  resources :cards

  resources :users 
  resources :sessions
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  get "sign_up" => "users#new", :as => "sign_up"
  get "user_show" => "users#show", :as => "user_show"
  get "change_pass" => "users#change_pass", :as => "change_pass"
  put "pass_update" => "users#pass_update", :as => "pass_update"
  
  get "book_show" => "memowords#book_show", :as => "book_show"
  get "book1" => "memowords#book1", :as => "book1"
  get "book2" => "memowords#book2", :as => "book2"
  get "book3" => "memowords#book3", :as => "book3"
  get "memowords/edit" => "memowords#book_edit", :as => "memowords_edit"
  
  get "addtestfile" => "cards#testfile", :as => "addtestfile"
  
  resources :memowords
  
  root :to => "sessions#new"
  

end

app/models/user.rb
 # encoding : utf-8
class User < ActiveRecord::Base
  attr_accessible :email, :log_in_name, :name,:suspend,:password,:password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  
  has_many :cards
  
    validates :password,
   :presence => {:message => 'パスワードを入力してください'},:on => :create,
   :length   => {:minimum => 8, :message => 'パスワードは8桁以上入力してください'},
   :format   => {:with => /^\w+$/, :message => '半角英数字のみで入力してください'},
   :confirmation => {:message => '２回入力したパスワードが一致しません、パスワードを正しく入力してください'}
  
  validates :email,
   :presence => {:message => 'メールアドレスが入力されていません'},
   :uniqueness => {:message => 'すでに登録されているメールアドレスです。違うメールアドレスを入力してください'}
   
  validates :log_in_name,
   :presence => {:message => 'ログインネームが入力されていません'},
   :format   => {:with => /^\w+$/, :message => '半角英数字のみで入力してください'},
   :uniqueness => {:message => 'そのログインネームはすでに使われています。違うログインネームを入力してください'}
   
  validates :name,
   :presence => {:message => '名前が入力されていません'},
   :format   => {:with => /^\w+$/, :message => '半角英数字のみで入力してください'},
   :uniqueness => {:message => 'すでに使われている名前です。違う名前を入力してください'}
   
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
    end
  end
  
  def self.authenticate(log_in_name,password)
    user = find_by_log_in_name(log_in_name)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)
      user
    else
      nil
    end
  end
  
  def self.check_password(user_id,password)
    user = find(user_id)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)
      true
    else
      nil
    end
  end
  
end

app/controllers/users_controller.rb
# encoding : utf-8
class UsersController < ApplicationController
  skip_before_filter :session_check ,:session_expire, only: ['new','create']
  skip_before_filter :admin, except: ['index','edit','update','destroy']
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(session[:user_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(session[:user_id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: 'ユーザーが登録完了しました' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  def pass_update
    pass = params[:pass]
    @user = User.find(session[:user_id])
    if User.check_password(session[:user_id],pass[:oldpassword])&& pass[:newpassword] == pass[:confirmation]
      
      @user.password = pass[:newpassword]
      
      respond_to do |format|
        if @user.save
          format.html { redirect_to user_show_url, notice: 'パスワードを変更しました' }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { render action: "new" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :back, notice: '入力値が不正です'
    end
     
    
    #else
    #  redirect_to :back , notice: '現在のパスワードが間違っています' 
    #end    
  end
  def change_pass

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :log_in_name %><br />
    <%= f.text_field :log_in_name %>
  </div>
  <div class="field">
    <%= f.label :suspend %><br />
    <%= f.text_field :suspend %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/change_pass.html.erb
<div id="change_pass">
<h1>パスワード変更</h1>
<%= form_tag(pass_update_path ,{:method => 'put'}) do %>
	<p>確認のため今のパスワードを入力してください</p>
	<div class="field">
		<%= label :pass,:oldpassword ,"現在のパスワード"%> <br />
		<%= password_field :pass,:oldpassword ,{:size => 40 } %>
	</div>
	<p>新しいパスワードを入力して”パスワード変更”をクリックしてください</p>
	<div class="field">
		<%= label :pass,:newpassword,"新しいパスワード" %> <br />
		<%= password_field  :pass,:newpassword ,{:size => 40 } %><br /><br />
		
		<%= label :pass,:confirmation　,"もう一度入力してください" %> <br />
		<%= password_field :pass,:confirmation ,{:size => 40 } %>
	</div>
	
	<%= submit_tag 'パスワード変更'%>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password hash</th>
    <th>Password salt</th>
    <th>Log in name</th>
    <th>Suspend</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password_hash %></td>
    <td><%= user.password_salt %></td>
    <td><%= user.log_in_name %></td>
    <td><%= user.suspend %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<div id="user_new">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <span>注意：登録した情報は必ずメモを取ってください。<br />
  	ログインIDやパスワードを忘れてしまった場合、管理者でもわからないのでログインできなくなります。
  </span>
  <fieldset>
	  <legend>名前とメールアドレス</legend>
	  <p><strong>名前</strong>は掲示板やチャットルームで表示される名前です。</p>

	  <div class="field">
	    <%= f.label :name,"名前" %><br />
	    <%= f.text_field :name %>
	  </div>
	  <p><strong>メールアドレス</strong>は必ず連絡の付くアドレスを登録してください。<br />
	  	Zsdouからお知らせがある場合に利用します。
	  </p>
	  <div class="field">
	    <%= f.label :email,"メールアドレス" %><br />
	    <%= f.text_field :email %>
	  </div>
  </fieldset>
  <fieldset>
  	  <legend>ログインIDとパスワード</legend>
  	  <p><strong>ログインID</strong>はセキュリティ上の観点から上で登録した名前とは違うものを設定してください。</p>
	  <div class="field">
	    <%= f.label :log_in_name,"ログインID" %><br />
	    <%= f.text_field :log_in_name %>
	  </div>
	  <p><strong>パスワード</strong>は半角英数で８桁以上を設定してください。</p>
	  <div class="field">
	    <%= f.label :password,"パスワード" %><br />
	    <%= f.password_field :password %>
	  </div>
	  <div class="field">
	    <%= f.label :password_confirmation,"確認のためもう一度パスワードを入力してください" %><br />
	    <%= f.password_field :password_confirmation %>
	  </div>
  </fieldset>
  <div class="actions">
    <%= f.submit "ユーザー登録"%>
  </div>
<% end %>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div id="user_show">
	<h1>ユーザー情報</h1><span><%= link_to 'パスワードを変更する', change_pass_path %> </span>
	<p>Nameは掲示板等に書き込んだときに表示される名前です。</p>
	<div>
		<p>
		  <b>Name:</b>
		  <%= @user.name %>
		</p>
	</div>
	<p>Log_in_IDはログインするときに使用します。</p>
	<div>
		<p>
 		 <b>Log in ID:</b>
 		 <%= @user.log_in_name %>
		</p>
	</div>
	<p>Emailは今のところ用途はありませんが、そのうち当サイトからのお知らせを送ることがあるかもしれません。</p>
	<div>
		<p>
 		 <b>Email:</b>
		 <%= @user.email %>
		</p>
	</div>
</div>
<%= session[:user_id] %>