config/routes.rb
Zsdou::Application.routes.draw do 
  

  resources :listing_cards

  resources :cards

  resources :users 
  resources :sessions
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  get "sign_up" => "users#new", :as => "sign_up"
  get "user_show" => "users#show", :as => "user_show"
  get "change_pass" => "users#change_pass", :as => "change_pass"
  put "pass_update" => "users#pass_update", :as => "pass_update"
  
  get "book_show" => "memowords#book_show", :as => "book_show"
  get "book1" => "memowords#book1", :as => "book1"
  get "book2" => "memowords#book2", :as => "book2"
  get "book3" => "memowords#book3", :as => "book3"
  get "memowords/edit" => "memowords#book_edit", :as => "memowords_edit"
  
  get "addtestfile" => "cards#testfile", :as => "addtestfile"
  
  resources :memowords
  
  root :to => "sessions#new"
  

end

app/models/memoword.rb
# coding : utf-8
class Memoword < ActiveRecord::Base
  attr_accessible  :comment, :division, :title
  belongs_to :user
  has_many :listing_cards
  has_many :cards, :through => :listing_cards
  
  validates :division,:title,
    :length => {:maximum => 40, :message => '40文字以下にしてください'}
  
  validates :comment,
    :length => {:maximum => 400, :message => '400文字以下にしてください'}
    
    
end

app/controllers/memowords_controller.rb
# encoding : utf-8
class MemowordsController < ApplicationController
    skip_before_filter :admin, except: ['index','new','show','edit','create','destroy']
  # GET /memowords
  # GET /memowords.json
  def book_show
    #book_initを初回だけに出来る方法は無いものか
    book_init(params[:num].to_i)
    @cards = @memoword.cards.page(params[:page]).per(10)
  end
  def book1
    book_number = 1
    book_init(book_number)
  end
  def book2
    book_number = 2
    book_init(book_number)
  end
  def book3
    book_number = 3
    book_init(book_number)
  end
  def book_edit
    @memoword = Memoword.find(session[:memoword_id])
  end
  def index
    @memowords = Memoword.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memowords }
    end
  end

  # GET /memowords/1
  # GET /memowords/1.json
  def show
    @memoword = Memoword.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @memoword }
    end
  end

  # GET /memowords/new
  # GET /memowords/new.json
  def new
    @memoword = Memoword.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @memoword }
    end
  end

  # GET /memowords/1/edit
  def edit
    @memoword = Memoword.find(session[:memoword_id])
  end

  # POST /memowords
  # POST /memowords.json
  def create
    @memoword = Memoword.new(params[:memoword])

    respond_to do |format|
      if @memoword.save
        format.html { redirect_to @memoword, notice: 'Memoword was successfully created.' }
        format.json { render json: @memoword, status: :created, location: @memoword }
      else
        format.html { render action: "new" }
        format.json { render json: @memoword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memowords/1
  # PUT /memowords/1.json
  def update
    @memoword = Memoword.find(params[:id])

    respond_to do |format|
      if @memoword.update_attributes(params[:memoword])
        redirect_book = "book" + @memoword.number.to_s
        #format.html { redirect_to @memoword, notice: 'Memoword was successfully updated.' }
        format.html { redirect_to :action => redirect_book, notice: 'Memoword was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @memoword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memowords/1
  # DELETE /memowords/1.json
  def destroy
    @memoword = Memoword.find(params[:id])
    @memoword.destroy

    respond_to do |format|
      format.html { redirect_to memowords_url }
      format.json { head :no_content }
    end
  end
  
  private
  def book_init(book_number)
    @memoword = Memoword.find_by_number_and_user_id(book_number,session[:user_id])
    
    unless @memoword
      @memoword = Memoword.new
      @memoword.number = book_number
      @memoword.division = "分類を入力してください"
      @memoword.title = "bookのタイトルを自分で決めることが出来ます"
      @memoword.comment = "横の編集ボタンを押せば、分類、タイトル、本の簡単な説明を入力変更できます"
      @memoword.user_id = session[:user_id]
      
      this_book = 'book' + book_number.to_s
    
      respond_to do |format|
        if @memoword.save
          format.html { render :action => this_book, notice: '初期化に成功しました' }
          format.json { render json: @memoword, status: :created, location: @memoword }
        else
          #format.html { render action: "new" }
          format.html { redirect_to root_url, notice: '初期化に失敗しました　暫くしてからアクセスしてください' }
          format.json { render json: @memoword.errors, status: :unprocessable_entity }
        end
      end
    end
    session[:memoword_id] = @memoword.id
    @list = @memoword.listing_cards.order('created_at DESC').limit(5)
  end
  
end

app/helpers/memowords_helper.rb
module MemowordsHelper
end

app/views/memowords/_edit_for_admin.html.erb
<%= form_for(@memoword) do |f| %>
  <% if @memoword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memoword.errors.count, "error") %> prohibited this memoword from being saved:</h2>

      <ul>
      <% @memoword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :division %><br />
    <%= f.text_field :division %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :cards_ary %><br />
    <%= f.text_area :cards_ary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memowords/_form.html.erb
<div class="form">
	<%= form_for(@memoword) do |f| %>
	  <% if @memoword.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@memoword.errors.count, "error") %> prohibited this memoword from being saved:</h2>
	
	      <ul>
	      <% @memoword.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
	  <div class="field">
	    <%= f.label :division,"分類" %><br />
	    <%= f.text_field :division %>
	  </div>
	  <div class="field">
	    <%= f.label :title,"タイトル" %><br />
	    <%= f.text_field :title %>
	  </div>
	  <div class="field">
	    <%= f.label :comment,"コメント" %><br />
	    <%= f.text_area :comment ,{:rows => 5}%>
	  </div>
	  
	  <div class="actions">
	    <%= f.submit '更新ボタン'%>
	  </div>
	<% end %>
</div>

app/views/memowords/_info.html.erb
<div id="book_info">
	<h1><%= "Book" + @memoword.number.to_s %></h1>
	<div>
		<h2>タイトル：<%= @memoword.title %></h1>
		<h2>分類：<%= @memoword.division %></h2>
		<h3>説明：</h3>
		<%= @memoword.comment %>
	</div>
	<%= link_to "編集", memowords_edit_path %>
	<br />
</div>
<%= render 'cards/cardlist'%>
	

app/views/memowords/book1.html.erb
<%= render 'info' %>

app/views/memowords/book2.html.erb
<%= render 'info' %>

app/views/memowords/book3.html.erb
<%= render 'info' %>

app/views/memowords/book_edit.html.erb
<%= render 'form' %>

app/views/memowords/book_show.html.erb
<div class="book_show" >
	
<h1>Listing cards</h1>

<div class="jumpbox">
	<%= paginate @cards,:window => 0 %>
</div>

<table>
  <tr>
    <th>質問</th>
    <th id = 'answers'>答え&nbsp<span id= 'open'>全開</span>&nbsp&nbsp&nbsp<span id ='close'>全閉</span></th>
  </tr>

<% @cards.each_with_index do |card,i| %>
  <tr class = 'card' id = '<%= i %>' data-answer=<%= card.answer %> >
    <td><%= card.question %></td>
    <td>Clickすると答えが開きます</td>

  </tr>
<% end %>
</table>
<br />
<div class="jumpbox">
	<%= paginate @cards,:window => 0 %>
</div>

<br />

<%= link_to 'New Card', new_card_path %>

</div>

app/views/memowords/edit.html.erb
<h1>Editing memoword</h1>

<%= render 'form' %>

<%= link_to 'Show', @memoword %> |
<%= link_to 'Back', memowords_path %>

app/views/memowords/index.html.erb
<h1>Listing memowords</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Division</th>
    <th>Title</th>
    <th>Comment</th>
    <th>User</th>
    <th>Cards ary</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memowords.each do |memoword| %>
  <tr>
    <td><%= memoword.number %></td>
    <td><%= memoword.division %></td>
    <td><%= memoword.title %></td>
    <td><%= memoword.comment %></td>
    <td><%= memoword.user_id %></td>
    <td><%= memoword.cards_ary %></td>
    <td><%= link_to 'Show', memoword %></td>
    <td><%= link_to 'Edit', edit_memoword_path(memoword) %></td>
    <td><%= link_to 'Destroy', memoword, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Memoword', new_memoword_path %>

app/views/memowords/new.html.erb
<h1>New memoword</h1>

<%= render 'form' %>

<%= link_to 'Back', memowords_path %>

app/views/memowords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @memoword.number %>
</p>

<p>
  <b>Division:</b>
  <%= @memoword.division %>
</p>

<p>
  <b>Title:</b>
  <%= @memoword.title %>
</p>

<p>
  <b>Comment:</b>
  <%= @memoword.comment %>
</p>

<p>
  <b>User:</b>
  <%= @memoword.user_id %>
</p>

<p>
  <b>Cards ary:</b>
  <%= @memoword.cards_ary %>
</p>


<%= link_to 'Edit', edit_memoword_path(@memoword) %> |
<%= link_to 'Back', memowords_path %>