config/routes.rb
Zsdou::Application.routes.draw do 
  

  resources :listing_cards

  resources :cards

  resources :users 
  resources :sessions
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  get "sign_up" => "users#new", :as => "sign_up"
  get "user_show" => "users#show", :as => "user_show"
  get "change_pass" => "users#change_pass", :as => "change_pass"
  put "pass_update" => "users#pass_update", :as => "pass_update"
  
  get "book_show" => "memowords#book_show", :as => "book_show"
  get "book1" => "memowords#book1", :as => "book1"
  get "book2" => "memowords#book2", :as => "book2"
  get "book3" => "memowords#book3", :as => "book3"
  get "memowords/edit" => "memowords#book_edit", :as => "memowords_edit"
  
  get "addtestfile" => "cards#testfile", :as => "addtestfile"
  
  resources :memowords
  
  root :to => "sessions#new"
  

end

app/models/card.rb
# coding : utf-8
class Card < ActiveRecord::Base
  attr_accessible :answer, :division, :question
  belongs_to :user
  has_many :listing_cards
  has_many :memowords, :through => :listing_cards
  
  validates  :question,:answer,
   :presence => {:message => '何も書かれていません'},
   :length   => {:maximum => 400, :message => '文章が長すぎます、400文字以下にしてください'}
  
#  validate :division
  
#  validate :user_id

  
end

app/controllers/cards_controller.rb
# encoding : utf-8
class CardsController < ApplicationController
    skip_before_filter :admin, only: ['create','new','testfile']
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.page(params[:page]).per(7)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])
    @card.user_id = session[:user_id]

    respond_to do |format|
      if @card.save
        listingcard = ListingCard.new do |m|
          m.memoword_id = session[:memoword_id]
          m.card_id = @card.id
          m.memorized = false
        end
        listingcard.save
        #format.html {render action: "new" }
        format.html { redirect_to new_card_url, notice: 'カードは作成されBookに登録されました' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
  def testfile
    if session[:memoword_id]
      (1..100).each do |num|
      
        card = Card.new do |c|
          c.question = "質問#{num}"
          c.answer = "答え#{num}"
          c.division = "英語"
          c.user_id = session[:user_id]
        end
        card.save
        listingcard = ListingCard.new do |lc|
          lc.card_id = card.id
          lc.memoword_id = session[:memoword_id]
          lc.memorized = false
        end
        listingcard.save
      end
    end
    respond_to do |format|
      format.html { redirect_to book1_url }
      format.json { head :no_content }
    end    
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_cardlist.html.erb
<div id="cardlist">
<h1>カード一覧</h1>

<table>
  <tr>
  	<th>㌻</th>
  	<th>分類</th>
    <th>質問</th>
    <th>答え</th>

  </tr>

<% @memoword.cards.each_with_index do |card,i| %>
  <tr>
  	<td><%= (i/10+1) %></td>
  	<td><%= card.division %></td>
    <td><%= card.question %></td>
    <td><%= card.answer %></td>
  </tr>
<% end %>
</table>
</div>


<%= link_to 'New Card', new_card_path %>

app/views/cards/_form.html.erb
<div id="new_card">

	<%= form_for(@card) do |f| %>
	  <% if @card.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>
	
	      <ul>
	      <% @card.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  <div class="field">
	    <%= f.label :division,"分類" %><br />
	    <%= f.text_field :division %>
	  </div>
	
	  <div class="field">
	    <%= f.label :question,"質問" %><br />
	    <%= f.text_area :question,{:cols => 40 ,:rows => 5}%>
	  </div>
	  <div class="field">
	    <%= f.label :answer,"答え" %><br />
	    <%= f.text_area :answer,{:cols => 40 ,:rows => 5} %>
	  </div>
	
	  <div class="actions">
	    <%= f.submit '作成ボタン'%>
	  </div>
	<% end %>
</div>
<div class="comment">
	<h1>使い方</h1>
	<div>
		<p><span>分類</span>：分類は空欄でも構いません。ですが何かしら入力していただければ今後より便利な機能が追加されたときに良いことがあるかもしれません。</p>
		
		<p><span>質問</span>：単語帳を開いたとき、左側に表示されている部分になります。</p>
		
		<p><span>答え</span>：単語帳を開いたときに、右側の隠された部分になります。</p>
	</div>
</div>
	

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Answer</th>
    <th>Division</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<%= paginate @cards %>
<% @cards.each do |card| %>
  <tr>
    <td><%= card.question %></td>
    <td><%= card.answer %></td>
    <td><%= card.division %></td>
    <td><%= card.user_id %></td>
    <td><%= link_to 'Show', card %></td>
    <td><%= link_to 'Edit', edit_card_path(card) %></td>
    <td><%= link_to 'Destroy', card, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= paginate @cards %><br />
<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>新規カード作成</h1>

<%= render 'form' %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @card.question %>
</p>

<p>
  <b>Answer:</b>
  <%= @card.answer %>
</p>

<p>
  <b>Division:</b>
  <%= @card.division %>
</p>

<p>
  <b>User:</b>
  <%= @card.user_id %>
</p>


<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>