config/routes.rb
Zsdou::Application.routes.draw do 
  

  resources :listing_cards

  resources :cards

  resources :users 
  resources :sessions
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  get "sign_up" => "users#new", :as => "sign_up"
  get "user_show" => "users#show", :as => "user_show"
  get "change_pass" => "users#change_pass", :as => "change_pass"
  put "pass_update" => "users#pass_update", :as => "pass_update"
  
  get "book_show" => "memowords#book_show", :as => "book_show"
  get "book1" => "memowords#book1", :as => "book1"
  get "book2" => "memowords#book2", :as => "book2"
  get "book3" => "memowords#book3", :as => "book3"
  get "memowords/edit" => "memowords#book_edit", :as => "memowords_edit"
  
  get "addtestfile" => "cards#testfile", :as => "addtestfile"
  
  resources :memowords
  
  root :to => "sessions#new"
  

end

app/views/layouts/_navi.html.erb
<div id="navi">
	<h1>Memoword</h1>
	<table>
		<tr>
			<td><%= link_to "Book1", book1_path %></td>
			<td><%= link_to "Book2", book2_path %></td>
			<td><%= link_to "Book3", book3_path %></td>
		</tr>
		<tr>
			<td><%= link_to "単語帳１",:controller => "memowords",:action => "book_show",:num => '1'%></td>
			<td><%= link_to "単語帳2",:controller => "memowords",:action => "book_show",:num => '2'%></td>
			<td><%= link_to "単語帳3",:controller => "memowords",:action => "book_show",:num => '3'%></td>
		</tr>
	</table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zsdou</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id ='top_tittle'><span>ZSdou.net</span><br />
		<% if current_user %>
		名前："<%= current_user.name %>”としてログイン中です　もし別人であればログアウトしてください。  <br />
		<% end %>
	</div>
	
	<div id ='user_nav'>

		<% if current_user %> 
			名前:"<%= current_user.name %>”<br />
			<%= link_to "ログアウト", log_out_path %><br />
			<%= link_to "ユーザー情報", user_show_path %>
		<% else %>  
    		<%= link_to "ユーザー登録", sign_up_path %><br /> 
    		<%= link_to "ログイン", log_in_path %>  
  		<% end %>
  	</div> 
  	<div style="clear: left"></div>
  	<br />

<%= render  'layouts/navi.html' %>

<br />

<%= notice %>
  <% flash.each do |name, msg| %>  
    <%= content_tag :div, msg, :id => "flash#{name}" %>  
  <% end %> 

  
<%= yield %>

</body>
</html>